=== sayihhamza/UML-Diagrams-Generator/resources/projectModel.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="relationType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="DEPENDENCY" />
            <xs:enumeration value="ASSOCIATION" />
            <xs:enumeration value="AGGREGATION" />
            <xs:enumeration value="COMPOSITION" />
            <xs:enumeration value="REALISATION" />
            <xs:enumeration value="GENERALIZATION" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="visibility">
        <xs:restriction base="xs:string">
            <xs:enumeration value="+" />
            <xs:enumeration value="-" />
            <xs:enumeration value="~" />
            <xs:enumeration value="#" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="project">
        <xs:sequence>
            <xs:element name="packages" type="packages" />
            <xs:element name="relations" type="relations" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" />
    </xs:complexType>
    <xs:complexType name="packages">
        <xs:sequence>
            <xs:element name="package" type="package" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="package">
        <xs:sequence>
            <xs:element name="classes" type="classes" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:ID" />
    </xs:complexType>
    <xs:complexType name="classes">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="class" type="modelType" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="interface" type="modelType" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="enumeration" type="enumeration" minOccurs="0" maxOccurs="unbounded" />
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="modelType">
        <xs:sequence>
            <xs:element name="fields" type="fields" minOccurs="0" />
            <xs:element name="methods" type="methods" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:ID" />
    </xs:complexType>
    <xs:complexType name="enumeration">
        <xs:sequence>
            <xs:element name="constants" type="constants" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:ID" />
    </xs:complexType>
    <xs:complexType name="fields">
        <xs:sequence>
            <xs:element name="field" type="field" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="field">
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="type" type="xs:string" />
        <xs:attribute name="visibility" type="visibility" />
    </xs:complexType>

    <xs:complexType name="methods">
        <xs:sequence>
            <xs:element name="method" type="method" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="method">
        <xs:sequence>
            <xs:element name="parameters" type="parameters" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="returnType" type="xs:string" />
        <xs:attribute name="visibility" type="visibility" />
    </xs:complexType>
    <xs:complexType name="parameters">
        <xs:sequence>
            <xs:element name="parameter" type="parameter" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="parameter">
        <xs:attribute name="type" type="xs:string" />
    </xs:complexType>
    <xs:complexType name="constants">
        <xs:sequence>
            <xs:element name="constant" type="constant" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="constant">
        <xs:attribute name="value" type="xs:string" />
    </xs:complexType>
    <xs:complexType name="relations">
        <xs:sequence>
            <xs:element name="relation" type="relation" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="relation">
        <xs:attribute name="parent" type="xs:IDREF" />
        <xs:attribute name="child" type="xs:IDREF" />
        <xs:attribute name="type" type="relationType" />
    </xs:complexType>
    <xs:element name="project" type="project"></xs:element>
</xs:schema>

=== sayihhamza/UML-Diagrams-Generator/resources/projectModel.xml
<?xml version="1.0" encoding="UTF-8"?><project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="example" xsi:noNamespaceSchemaLocation="projectModel.xsd">
    <packages>
        <package name="org.mql.java.example.classes">
            <classes>
                <class name="org.mql.java.example.classes.Bike..FuelBike">
                    <fields/>
                    <methods>
                        <method name="org.mql.java.example.classes.Bike$FuelBike" returnType="" visibility="+">
                            <parameters>
                                <parameter type="org.mql.java.example.classes.Bike"/>
                            </parameters>
                        </method>
                    </methods>
                </class>
                <class name="org.mql.java.example.classes.Bike">
                    <fields>
                        <field name="driver" type="org.mql.java.example.classes.Driver" visibility="-"/>
                        <field name="wheels" type="java.util.List&lt;org.mql.java.example.classes.Wheel&gt;" visibility="-"/>
                        <field name="energeyType" type="org.mql.java.example.enums.EnergeyType" visibility="-"/>
                    </fields>
                    <methods>
                        <method name="toString" returnType="java.lang.String" visibility="+"/>
                        <method name="makeSound" returnType="void" visibility="+"/>
                        <method name="testDependency" returnType="void" visibility="~">
                            <parameters>
                                <parameter type="org.mql.java.example.classes.Car"/>
                                <parameter type="org.mql.java.example.classes.Driver"/>
                            </parameters>
                        </method>
                        <method name="org.mql.java.example.classes.Bike" returnType="" visibility="+">
                            <parameters>
                                <parameter type="org.mql.java.example.classes.Driver"/>
                                <parameter type="java.util.List&lt;org.mql.java.example.classes.Wheel&gt;"/>
                            </parameters>
                        </method>
                    </methods>
                </class>
                <class name="org.mql.java.example.classes.Car">
                    <fields>
                        <field name="driver" type="org.mql.java.example.classes.Driver" visibility="-"/>
                        <field name="wheels" type="java.util.List&lt;org.mql.java.example.classes.Wheel&gt;" visibility="-"/>
                        <field name="energeyType" type="org.mql.java.example.enums.EnergeyType" visibility="-"/>
                    </fields>
                    <methods>
                        <method name="toString" returnType="java.lang.String" visibility="+"/>
                        <method name="inCaseOfAccidentDriveBike" returnType="void" visibility="+">
                            <parameters>
                                <parameter type="org.mql.java.example.classes.Bike"/>
                            </parameters>
                        </method>
                        <method name="makeSound" returnType="void" visibility="+"/>
                        <method name="getWheels" returnType="java.util.List&lt;org.mql.java.example.classes.Wheel&gt;" visibility="+"/>
                        <method name="org.mql.java.example.classes.Car" returnType="" visibility="+">
                            <parameters>
                                <parameter type="org.mql.java.example.classes.Driver"/>
                                <parameter type="org.mql.java.example.enums.EnergeyType"/>
                                <parameter type="java.util.List&lt;org.mql.java.example.classes.Wheel&gt;"/>
                            </parameters>
                        </method>
                    </methods>
                </class>
                <class name="org.mql.java.example.classes.Driver">
                    <fields>
                        <field name="name" type="java.lang.String" visibility="-"/>
                        <field name="primaryVehicle" type="org.mql.java.example.classes.Vehicle" visibility="-"/>
                        <field name="secondaryVehicle" type="org.mql.java.example.classes.Vehicle" visibility="-"/>
                    </fields>
                    <methods>
                        <method name="toString" returnType="java.lang.String" visibility="+"/>
                        <method name="org.mql.java.example.classes.Driver" returnType="" visibility="+">
                            <parameters>
                                <parameter type="java.lang.String"/>
                                <parameter type="org.mql.java.example.classes.Vehicle"/>
                                <parameter type="org.mql.java.example.classes.Vehicle"/>
                            </parameters>
                        </method>
                    </methods>
                </class>
                <class name="org.mql.java.example.classes.Vehicle">
                    <methods>
                        <method name="org.mql.java.example.classes.Vehicle" returnType="" visibility="+"/>
                    </methods>
                </class>
                <class name="org.mql.java.example.classes.Wheel">
                    <methods>
                        <method name="org.mql.java.example.classes.Wheel" returnType="" visibility="+"/>
                    </methods>
                </class>
            </classes>
        </package>
        <package name="org.mql.java.example.enums">
            <classes>
                <enumeration name="org.mql.java.example.enums.EnergeyType">
                    <constants>
                        <constant value="GASOLINE"/>
                        <constant value="DIESEL"/>
                        <constant value="ELECTRIC"/>
                        <constant value="LEGS"/>
                    </constants>
                </enumeration>
            </classes>
        </package>
        <package name="org.mql.java.example.interfaces">
            <classes>
                <interface name="org.mql.java.example.interfaces.Sound">
                    <methods>
                        <method name="makeSound" returnType="void" visibility="+"/>
                    </methods>
                </interface>
            </classes>
        </package>
    </packages>
    <relations>
        <relation child="org.mql.java.example.classes.Bike..FuelBike" parent="org.mql.java.example.classes.Bike" type="COMPOSITION"/>
        <relation child="org.mql.java.example.classes.Bike" parent="org.mql.java.example.classes.Bike..FuelBike" type="COMPOSITION"/>
        <relation child="org.mql.java.example.classes.Bike" parent="org.mql.java.example.classes.Car" type="DEPENDENCY"/>
        <relation child="org.mql.java.example.classes.Bike" parent="org.mql.java.example.classes.Vehicle" type="GENERALIZATION"/>
        <relation child="org.mql.java.example.classes.Bike" parent="org.mql.java.example.interfaces.Sound" type="REALISATION"/>
        <relation child="org.mql.java.example.classes.Car" parent="org.mql.java.example.classes.Bike" type="DEPENDENCY"/>
        <relation child="org.mql.java.example.classes.Car" parent="org.mql.java.example.classes.Vehicle" type="GENERALIZATION"/>
        <relation child="org.mql.java.example.classes.Car" parent="org.mql.java.example.interfaces.Sound" type="REALISATION"/>
        <relation child="org.mql.java.example.classes.Driver" parent="org.mql.java.example.classes.Bike" type="AGGREGATION"/>
        <relation child="org.mql.java.example.classes.Driver" parent="org.mql.java.example.classes.Car" type="AGGREGATION"/>
        <relation child="org.mql.java.example.classes.Vehicle" parent="org.mql.java.example.classes.Driver" type="AGGREGATION"/>
        <relation child="org.mql.java.example.classes.Wheel" parent="org.mql.java.example.classes.Bike" type="COMPOSITION"/>
        <relation child="org.mql.java.example.classes.Wheel" parent="org.mql.java.example.classes.Car" type="COMPOSITION"/>
        <relation child="org.mql.java.example.enums.EnergeyType" parent="org.mql.java.example.classes.Bike" type="ASSOCIATION"/>
        <relation child="org.mql.java.example.enums.EnergeyType" parent="org.mql.java.example.classes.Car" type="COMPOSITION"/>
    </relations>
</project>
